<?php
use \Drupal\Core\Field\BaseFieldDefinition;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\scitalk_base\ScitalkServices\ReferenceIDGeneratorInterface;

/**
 * Implements hook_theme().
 */
function scitalk_stats_theme($existing, $type, $theme, $path) {
  return [
    'scitalk_stats_block' => [
      'variables' => [
        'title' => '', 
        'repositories' => [],
        'collections' => [],
        'talks' => ''
      ],
      'template' => 'block--scitalk-stats'
    ],
  ];
}
